name: Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.18-bullseye
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: make test

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ test ]
    runs-on: ubuntu-latest
    container: golang:1.18-bullseye
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: make build-release

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./bin/gobundle"
          token: ${{ secrets.GITHUB_TOKEN }}
