name: Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.18-bullseye
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make test

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ test ]
    runs-on: ubuntu-latest
    container: golang:1.18-bullseye
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set tag in env
        # https://stackoverflow.com/a/58178121/6645446
        run: echo "BUILD_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Make packages
        run: make package-all

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./packages/*"
          token: ${{ secrets.GITHUB_TOKEN }}
